/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FooterDescription: typeof import('./components/FooterDescription.vue')['default']
    HeadDescription: typeof import('./src/components/HeadDescription.vue')['default']
    Header: typeof import('./components/header/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/sidebar/index.vue')['default']
  }
}
