/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/index/AboutMe.vue')['default']
    ArticleSearch: typeof import('./components/teaParty/ArticleSearch.vue')['default']
    ArticleShow: typeof import('./components/teaParty/ArticleShow.vue')['default']
    BlogInfo: typeof import('./components/index/BlogInfo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    FooterDescription: typeof import('./components/FooterDescription.vue')['default']
    HandleBottom: typeof import('./components/music/handleBottom.vue')['default']
    HandleButton: typeof import('./components/music/handleButton.vue')['default']
    HeadDescription: typeof import('./src/components/HeadDescription.vue')['default']
    Header: typeof import('./components/header/Header.vue')['default']
    IndexArticle: typeof import('./components/index/IndexArticle.vue')['default']
    MySkills: typeof import('./components/index/MySkills.vue')['default']
    NewTrends: typeof import('./components/index/NewTrends.vue')['default']
    RecommendedBooks: typeof import('./components/index/RecommendedBooks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/sidebar/index.vue')['default']
    Title: typeof import('./components/public/Title.vue')['default']
  }
}
